/*
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: MIT
 */

#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, rgba32f) uniform image2D dst;
layout(set = 0, binding = 1, rgba32f) readonly uniform image2D src;

void main()
{
    const ivec2 coord = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    const vec4 val = imageLoad(src, coord);
    imageStore(dst, coord, val);
}
